### ISSUE TITLE
[BUG] SCOPENPORTS reporting conflicts for system servers

### ISSUE THREAD

**Issue by AndyYouens** [ThePrez/ServiceCommander-IBMi#101]
**Describe the bug**
SCOPENPORTS reports a liveliness check.  It reports 2 errors on system definitions, for example, SSHD, FTP etc.

WARNING: the following services all have conflicting definitions for liveliness check 'PORT:22':
    system_sshd (System Secure Shell server)
    sshd (System Secure Shell server)

**To Reproduce**
run scopenports

**Expected behavior**
not to show any conflict

**Verbose output**
Run the command with the `-v` option and share the output here.

scopenports -v
Initializing service myscript
Loading yaml service definition from file /QOpenSys/etc/sc/services/myscript.yml
Initializing service system_admin1
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_admin1.yaml
Initializing service system_admin2
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_admin2.yaml
Initializing service system_admin3
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_admin3.yaml
Initializing service system_admin4
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_admin4.yaml
Initializing service system_admin5
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_admin5.yaml
Initializing service system_ajs
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_ajs.yaml
Initializing service system_as-central
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-central.yaml
Initializing service system_as-database
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-database.yaml
Initializing service system_as-dtaq
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-dtaq.yaml
Initializing service system_as-file
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-file.yaml
Initializing service system_as-netprt
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-netprt.yaml
Initializing service system_as-rmtcmd
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-rmtcmd.yaml
Initializing service system_as-signon
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-signon.yaml
Initializing service system_as-sts
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-sts.yaml
Initializing service system_as-svrmap
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_as-svrmap.yaml
Initializing service system_cimom
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_cimom.yaml
Initializing service system_dbgsvr
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_dbgsvr.yaml
Initializing service system_ddm
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_ddm.yaml
Initializing service system_directoryserver
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_directoryserver.yaml
Initializing service system_ftp
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_ftp.yaml
Initializing service system_http_admin
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_http_admin.yaml
Initializing service system_lpd
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_lpd.yaml
Initializing service system_netserver
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_netserver.yaml
Initializing service system_pop
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_pop.yaml
Initializing service system_rmc
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_rmc.yaml
Initializing service system_slp
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_slp.yaml
Initializing service system_smtp
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_smtp.yaml
Initializing service system_sptprx
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_sptprx.yaml
Initializing service system_sshd
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_sshd.yaml
Initializing service system_telnet
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_telnet.yaml
Initializing service system_ypsjsvr
Loading yaml service definition from file /QOpenSys/etc/sc/services/system/system_ypsjsvr.yaml
Initializing service as-central
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-central.yaml
Initializing service as-database
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-database.yaml
Initializing service as-dtaq
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-dtaq.yaml
Initializing service as-file
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-file.yaml
Initializing service as-netprt
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-netprt.yaml
Initializing service as-rmtcmd
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-rmtcmd.yaml
Initializing service as-signon
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-signon.yaml
Initializing service as-svrmap
Loading yaml service definition from file /HOME/ANDY/.sc/services/as-svrmap.yaml
Initializing service ddm
Loading yaml service definition from file /HOME/ANDY/.sc/services/ddm.yaml
Initializing service directoryserver
Loading yaml service definition from file /HOME/ANDY/.sc/services/directoryserver.yaml
Initializing service ftp
Loading yaml service definition from file /HOME/ANDY/.sc/services/ftp.yaml
Initializing service netserver
Loading yaml service definition from file /HOME/ANDY/.sc/services/netserver.yaml
Initializing service sshd
Loading yaml service definition from file /HOME/ANDY/.sc/services/sshd.yaml
Initializing service telnet
Loading yaml service definition from file /HOME/ANDY/.sc/services/telnet.yaml
Initializing service navigator
Loading yaml service definition from file /HOME/ANDY/.sc/services/navigator.yaml
Initializing service mariadb
Loading yaml service definition from file /HOME/ANDY/.sc/services/mariadb.yaml
Initializing service crond
Loading yaml service definition from file /HOME/ANDY/.sc/services/crond.yaml
Initializing service apache_framework
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_framework.yaml
Initializing service apache_helpdesk
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_helpdesk.yaml
Initializing service apache_students
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_students.yaml
Initializing service apache_ws_crm
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_ws_crm.yaml
Initializing service apache_apachedft
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_apachedft.yaml
Initializing service apache_f_files
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_files.yaml
Initializing service apache_f_contact
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_contact.yaml
Initializing service apache_f_crm
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_crm.yaml
Initializing service apache_f_mtd
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_mtd.yaml
Initializing service apache_f_quote
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_quote.yaml
Initializing service apache_f_support
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_support.yaml
Initializing service apache_f_train
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_f_train.yaml
Initializing service apache_intranet
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_intranet.yaml
Initializing service apache_iwadft
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_iwadft.yaml
Initializing service apache_school
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_school.yaml
Initializing service apache_t779
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_t779.yaml
Initializing service apache_ws_isws04
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_ws_isws04.yaml
Initializing service apache_ws_train
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_ws_train.yaml
Initializing service apache_zendsvr6
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_zendsvr6.yaml
Initializing service apache_zendsvr620160729085704
Loading yaml service definition from file /HOME/ANDY/.sc/services/apache_zendsvr620160729085704.yaml
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:1113':
    apache_framework (Apache server Framework)
    apache_f_support (Apache server f_support)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:1021':
    apache_f_quote (Apache server f_quote)
    apache_f_crm (Apache server f_crm)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:10083':
    apache_zendsvr6 (Apache server zendsvr6)
    apache_zendsvr620160729085704 (Apache server zendsvr620160729085704)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8471':
    as-database (System *DATABASE Host Server)
    system_as-database (System *DATABASE Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:445':
    netserver (System NetServer)
    system_netserver (System NetServer)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8470':
    system_as-central (System *CENTRAL Host Server)
    as-central (System *CENTRAL Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:446':
    system_ddm (System DDM server)
    ddm (System DDM server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8473':
    as-file (System *FILE Host Server)
    system_as-file (System *FILE Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8472':
    system_as-dtaq (System *DTAQ Host Server)
    as-dtaq (System *DTAQ Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:23':
    system_telnet (System Telnet server)
    telnet (System Telnet server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8475':
    system_as-rmtcmd (System *RMTCMD Host Server)
    as-rmtcmd (System *RMTCMD Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:449':
    as-svrmap (System *SVRMAP Host Server)
    system_as-svrmap (System *SVRMAP Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:22':
    system_sshd (System Secure Shell server)
    sshd (System Secure Shell server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8474':
    system_as-netprt (System *NETPRT Host Server)
    as-netprt (System *NETPRT Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:21':
    ftp (System FTP server)
    system_ftp (System FTP server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8476':
    as-signon (System *SIGNON Host Server)
    system_as-signon (System *SIGNON Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'JOBNAME:QHTTPSVR/ADMIN2':
    system_admin2 (IBM Navigator for i)
    navigator (IBM Navigator for i)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:80':
    apache_apachedft (Apache server apachedft)
    apache_intranet (intranet)
Address          Port    'sc' service name (and friendly name)
---------------  ------  --------------------------------------------
Found pre-existing service for ad hoc specs: System FTP server
0.0.0.0          21      ftp (System FTP server)
Found pre-existing service for ad hoc specs: System Secure Shell server
0.0.0.0          22      sshd (System Secure Shell server)
Found pre-existing service for ad h.

**Comment by ThePrez** [comment]
Sorry for this. Please run `sc_open_ports --cleanupv0` and see if that fixes it. I changed several things about how the system servers were handled, but if you ran `sc_open_ports` with v0.x, you can get conflicts

**Comment by AndyYouens** [comment]
Thanks for that.  I am using;
Name        : service-commander
Arch        : ppc64
Version     : 1.1.0

but still getting 2 warnings for each server
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:22':
    system_sshd (System Secure Shell server)
    sshd (System Secure Shell server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8474':
    system_as-netprt (System *NETPRT Host Server)
    as-netprt (System *NETPRT Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:21':
    system_ftp (System FTP server)
    ftp (System FTP server)

am I using the correct version?

**Comment by ThePrez** [comment]
v1.1.0 is best. The `--cleanupv0` option should have cleaned up the definitions you had from an earlier release, but that doesn't seem to be the case. Did you get any errors when you ran with `--cleanupv0`?

**Comment by AndyYouens** [comment]
no errors on running.

andy@GALATEA ~ $ scopenports --cleanupv10
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:8471':
    system_as-database (System *DATABASE Host Server)
    as-database (System *DATABASE Host Server)
WARNING: the following services all have conflicting definitions for liveliness check 'PORT:445':
    netserver (System NetServer)
    system_netserver (System NetServer)

**Comment by ThePrez** [comment]
Two things:
1. Sorry, the command I _meant to_ ask  you to run is `sc_install_defaults --cleanupv0` (oops!) 
2. `scopenports --cleanupv10` should have given you a warning since that's not a valid option for `scopenports`. I've opened #102 for that problem

What I believe happened here is:
- You ran `sc_install_defaults` using service commander v0.x, which created the definitions not prefixed with `_system`
- In v1.x, `sc_install_defaults` started prefixing those with `system_`
- You ran `sc_install_defaults` with service commander v1.x, resulting in the conflicts
- I didn't default to cleaning up those old ones by default because I didn't think anyone used `sc_install_defaults` with v0.x! (another oops)

**Comment by AndyYouens** [comment]
thanks for the explanation.  sc_intall_defaults --cleanupv0 got rid of the majority of the duplicates, except.

_WARNING: the following services all have conflicting definitions for liveliness check 'JOBNAME:QHTTPSVR/ADMIN2':
    navigator (IBM Navigator for i)
    system_admin2 (IBM Navigator for i)_

Certainly a great cleanup.

I agree with your explanation of what I did (I think! )

**Comment by ThePrez** [comment]
Great!
This command should finish the fixup:
```
rm `sc file navigator`
```
I have opened issue #103 to track the missing file on cleanup.

**Comment by AndyYouens** [comment]
All works fine now thanks.
