### ISSUE TITLE
[BUG] scopenports doesn't issue warning for unknown args

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#102]
**Describe the bug**

As discovered in [the discussion](https://github.com/ThePrez/ServiceCommander-IBMi/issues/101#issuecomment-1016201835) of #101, running `scopenports` with unknown args does not issue a warning. 

**Expected Behavior**
Running `scopenports --hahdhasdfhadsf` should issue a warning saying that the command line option is unrecognized

**Comment by AndyYouens** [comment]
Ok for me to pick up @ThePrez

**Comment by ThePrez** [comment]
Rock on!
