### ISSUE TITLE
[FEATURE-REQUEST] Overview of all groups

### ISSUE THREAD

**Issue by Bjarne-La** [ThePrez/ServiceCommander-IBMi#123]
The command "sc groups" may output a list of all groups that are defined in YAML configuration files or are predefined, such as the group "system". With the argument "--ignore-globals" only groups are shown that are defined within the users private YAML configuration files.

The command could look like this:
sc groups (--ignore-globals)

An output could look like this:
apache    
host_servers  
system
...

**Comment by ThePrez** [comment]
I like it!

**Comment by Bjarne-La** [comment]
> I like it!

Cool! I‘ve already made some changes to the code, but I wasn‘t able to commit my changes. I‘m a total beginner at git, but I will try again tomorrow!

**Comment by ThePrez** [comment]
Fixed by #124 
Thanks!
