### ISSUE TITLE
Does SC work with the "native" JDK 11? 

### ISSUE THREAD

**Issue by bdietz400** [ThePrez/ServiceCommander-IBMi#130]
Java 11 is available as an Installable Licensed program from the ESS site.

LICPGM     Option  Feature     Description 
5770JV1      19         5119        Java SE 11 64 bit

the install path is
/QOpenSys/QIBM/ProdData/JavaVM/jdk11/64bit

so the simple question is can ServiceCommander work with this version of Java or is the RPM version our only option?

**Comment by ThePrez** [comment]
Hi, Brian. Service Commander only runs with the RPM Java. It does not work with JV1.

**Comment by bdietz400** [comment]
I have no wish to *have to use JV1, it seemed to be strange to have the "same java" in different places.  One being an evaluation install

**Comment by ThePrez** [comment]
The two Java flavors work best for different types of workloads. Sorry this is a blocker in your environment. 😞 

There are some code comments with explanation for the RPM dependency here: 

https://github.com/ThePrez/ServiceCommander-IBMi/blob/88414df4b02afaa4ce107152ee2a2cffc8f7d819/src/main/java/jesseg/ibmi/opensource/ServiceCommander.java#L41
