### ISSUE TITLE
[BUG]Installing service defaults fails (pre-release v1.4.3)

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#171]
**Describe the bug**

I installed SC pre-release v1.4.3 from RPM (as descibed in issue #170) and ran the `sc_install_defaults` command.
The command failed with the following output:
```bash
→ sc_install_defaults
Cleaning up v0 files...
Cleaning up previously installed configurations...
  cleaning up previously-installed configuration zenddbi...
installing apache server apachedft
installing apache server iwadft
installing apache server zendphp7
installing apache server zendsvr6
installing Integrated Web Services (IWS) server IWS00105I...
OOPS!! Could not determine attributes for IWS server IWS00105I
```

I then tried installing the defaults without APACHE services (this time globally) - same error:
```bash
→ sc_install_defaults --global --noapache
Cleaning up v0 files...
Cleaning up previously installed configurations...
  cleaning up previously-installed configuration apache_apachedft...
  cleaning up previously-installed configuration apache_iwadft...
  cleaning up previously-installed configuration apache_zendphp7...
  cleaning up previously-installed configuration apache_zendsvr6...
installing Integrated Web Services (IWS) server IWS00105I...
OOPS!! Could not determine attributes for IWS server IWS00105I
```

**To Reproduce**

Install pre-release v1.4.3 and run the `sc_install_defaults` command.

**Expected behavior**

The `sc_install_defaults` command should run without ending in error with IWS server.

**Verbose output**
Run the command with the `-v` option and share the output here.

There is no option `-v` for `sc_install_defaults`.

But here is some additional output:

```bash
→ qsh -c "JAVA_TOOL_OPTIONS=-Dos400.stdio.convert=N /qibm/proddata/os/webservices/bin/getWebServicesServerProperties.sh -server IWS00105I"
IWS00240E - Server does not exist.
```

**Additional context**

**Comment by chrjorgensen** [comment]
Added output from calling the ```getWebServicesServerProperties.sh``` script manually.

**Comment by ThePrez** [comment]
Thanks for finding! Some of the `OOPS!!` is by design, since the server doesn't fully exist... but did your execution stop completely after that error?

**Comment by chrjorgensen** [comment]
Yes, it stopped after the OOPS!!... well, at least no more output from the command.

**Comment by chrjorgensen** [comment]
Ah, okay - found it...!

The initial query for IWS servers return `IWS00105I` when there are no IWS servers defined:

```
→ qsh -c "JAVA_TOOL_OPTIONS=-Dos400.stdio.convert=N /qibm/proddata/os/webservices/bin/listWebServicesServers.sh"
IWS00105I - No Web services servers are defined.
```

and the script just takes whatever is in the first column and use this as the IWS server name.
