### ISSUE TITLE
Show short name of service even if not running

### ISSUE THREAD

**Issue by m1h43l** [ThePrez/ServiceCommander-IBMi#190]
Currently (in 1.4.3 at least) the short name of the service is displayed in colors if service is running in the output of `sc check`. But if the service is not running the short name is not displayed. Thus I have to lookup the short name either by querying the config files or using sc list. It would be easier if the short name would also be displayed in the output of `sc check` no matter if the service is running or not.

**Comment by ThePrez** [comment]
@m1h43l , can you provide a screen shot of the behavior you are seeing? In my test environment, I see the short names of both running and non-running services and don't see anything obvious in the code that would cause this behavior

Example output on my test system
![image](https://user-images.githubusercontent.com/17914061/200608423-1cede234-9de7-43bb-b448-b711e8d06399.png)

**Comment by m1h43l** [comment]
![grafik](https://user-images.githubusercontent.com/10236415/201923743-5d34723e-8e2f-4418-8ed8-6036fe9a8b27.png)

The screenshot is taken in from a powershell. I have now tested it with a normal DOS Shell window (black background) ... and tada ... now I can see labels of the not running services. You have take a really inconvenient color for my eyes for these labels ;-) .

**Comment by chrjorgensen** [comment]
@ThePrez Maybe the color codes could be put in a config file for ServiceCommander?
Colors are very subjective and every user has their own preferences - and maybe configured the terminal to reflect this. A config file would allow the user to pick the favorite colors.
