### ISSUE TITLE
[BUG] scedit doesn't respect $EDITOR unless it is a fully qualified path

### ISSUE THREAD

**Issue by martintosney** [ThePrez/ServiceCommander-IBMi#191]
**Describe the bug**

I'm just trying out SC for the first time - it's pretty cool!

I tried `scedit` and read that it should respect the EDITOR variable. I found that it would always load `nano` instead.

Looking at the script, I think this is because I only had EDITOR set to `vim`, not `/QOpenSys/pkgs/bin/vim`. Fully qualifying the path makes it work as expected, but I've not found this to be required for other tools I've used.

Perhaps the script could resolve $EDITOR to a full path with `which`, before the test to see if it is executable?

**To Reproduce**

Set EDITOR to `vim` (with vim installed on the system); run `scedit` for a service.

**Expected behavior**

Service configuration is loaded into vim, not nano.

**Comment by ThePrez** [comment]
Thanks for finding and reporting!
