### ISSUE TITLE
[BUG] Logfile name uses wrong elements in timestamp

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#203]
**Describe the bug**

The generated logfile name was intended to use a name like `<timestamp>.<service>.<action>.log`. The timestamp format was specified as `yyyy-MM-dd-HH.mm.ss`. However, this is wrong when used in DB2 VARCHAR_FORMAT SQL function:

- `mm` does not specify minutes, but instead means month. To get the minutes, the `mi` specifier should be used.
- `HH` specifies 12 hour format, where it probably should be 24 hour format `HH24`.

**To Reproduce**

Check the logfiles generated by the current version of Service Commander.

**Expected behavior**

**Verbose output**
Run the command with the `-v` option and share the output here.

**Additional context**

**Comment by ThePrez** [comment]
Resolved by #204. Thanks!
