### ISSUE TITLE
[Q] Possibility to increase startup wait time? 

### ISSUE THREAD

**Issue by ravisankar-PIO** [ThePrez/ServiceCommander-IBMi#226]
My GitBucket application takes more than 60 seconds to start. Probably because of that, the application is not starting up!?

![image](https://github.com/ThePrez/ServiceCommander-IBMi/assets/139198015/de52709b-e274-4d30-9f2b-4f5da59f4e16)

![image](https://github.com/ThePrez/ServiceCommander-IBMi/assets/139198015/c0a79d9b-d3c2-4488-bcdc-dc2e6474ef63)

So I was wondering if it is possible to increase the startup time?

Thank you,
Ravi.

**Comment by chrjorgensen** [comment]
@ravisankar-PIO Add a line to your YAML file for the service, containing `startup_wait_time: nnn`, where `nnn` is the number of seconds to wait for the application to start.

For more information of what fields are available, check here:
https://github.com/ThePrez/ServiceCommander-IBMi?tab=readme-ov-file#optional-fields-that-are-often-neededwanted
