### ISSUE TITLE
[BUG] make install fails during chmod of existing sc yaml configs

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#39]
**Describe the bug**
I had the RPM version of SC installed and had created two services as two yaml files in the directory /QOpenSys/etc/sc/services.
This worked fine without any issue. However, I wanted to upgrade to the latest version to test the STRTCPSVR function.

When following the procedure for building the latest version from source, the build ran fine until it tried to run chmod against the existing yaml files:

![billede](https://user-images.githubusercontent.com/13275072/114886773-1d187080-9e08-11eb-88e9-1887cec3850a.png)

**To Reproduce**
Run make install with existing sc yaml configurations in /QOpenSys/etc/sc/services.

**Expected behavior**
Make install should complete without error and not fail during chmod. :-)

**Comment by ThePrez** [comment]
Fixed by #40 . Thanks!
