### ISSUE TITLE
[Q] How to submit ServiceCommander via scheduled jobs?

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#41]
Hi Jesse.

I have defined two services (NGINX instances serving two mirrors of IBM YUM repositories) and are able to start these in a bash session using the command `sc start all`.

Now I want to start the services with a scheduled job, so in WRKJOBSCDE I have defined a job with this command:
```
CALL PGM(QP2SHELL2) PARM('/QOpenSys/usr/bin/sh' '-c' '/QOpenSys/pkgs/bin/sc start all')
```

However, when running the ServiceCommander produces this error:
```
Error: Port Library failed to initialize: -1             
Error: Could not create the Java Virtual Machine.        
Error: A fatal exception has occurred. Program will exit.
```

How can I start ServiceCommander from a scheduled job? I guess it may be caused by some different path setting, but I need help on this one.

Best regards,
Christian

**Comment by richardschoen** [comment]
I believe you need to make sure to submit to a subsystem that allows more than 1 active thread at a time.  I normally use: QSYSNOMAX or QUSRNOMAX because they have unlimited threads.

**Comment by richardschoen** [comment]
Yep, that was the point of it.  I've had to write the same chunk of CL code for years and no-more :-)

**Comment by ThePrez** [comment]
I am on vacation and will look into your scenario in more detail when I return on Thursday. However the STRTCPSVR support might do the trick. Something like `STRTCPSVR *SC INSTANCE(*ALL)`

**Comment by chrjorgensen** [comment]
Hi Jesse "Travelman" ;-)

I upgraded the ServiceCommander to the latest version 0.2.1 and installed the STRTCPSVR option.

When I run the command `STRTCPSVR SERVER(*SC) INSTANCE('repo_server')`, I get the following in QPRINT:
```
WARNING: Argument 'start' unrecognized and will be ignored      
WARNING: Argument 'repo_server' unrecognized and will be ignored
Unsupported operation '!' requested                             
```

My service is called "repo_server" and the config is contained in the file `/QOpenSys/etc/sc/services/repo_server.yaml`:
```
name: IBM synchronized repository server  
dir: /QOpenSys/QIBM/UserData/rpm_repos/ibm
start_cmd: ./startServerBatch             
stop_cmd: ./stopServer                    
                                          
check_alive: port                         
check_alive_criteria: 2055                
```


Hope you have had a nice vacation.

Best regards,
Christian

**Comment by ThePrez** [comment]
@chrjorgensen, I believe the root cause is that the implementation uses a bash pipe (`|`) which is invariant and it was not being properly handled for your CCSID. 

I cut a new release with the fix. Please upgrade to the latest release, run the STRTCPSVR setup again (`/QOpenSys/pkgs/lib/sc/tcpsvr/install_sc_tcpsvr`), and evaluate. 

Thanks for your patience. Part of the justification for the STRTCPSVR support was to interact better with system functions like ADDJOBSCDE. I'm still not sure whether the threads issue mentioned earlier will be an impeding factor.

**Comment by ThePrez** [comment]
Looks like if ADDJOBSCDE is done with a job description that allows multiple threads like @richardschoen [mentioned](https://github.com/ThePrez/ServiceCommander-IBMi/issues/41#issuecomment-838765368), the thread issue shouldn't be a problem. Once you verify that ADDJOBSCDE works, we should open an issue for documentation around it. 
Thanks!

**Comment by chrjorgensen** [comment]
@ThePrez I installed the new release and reran the STRTCPSVR setup - and now it works! :+1:

When I run the command `STRTCPSVR SERVER(*SC) INSTANCE('repo_server')` I get the following QPRINT:
```
Performing operation 'START' on service 'repo_server'                                
Service 'IBM synchronized repository server' successfully started                    
For details, see log file at: /home/NCCJ/.sc/logs/2021-05-14-11.05.35.repo_server.log
```

And the ENDTCPSVR command works as well. Both command work in a job without multiple threads allowed - ALWMLTTHD(*NO).

Thanks for fixing this!

**Comment by chrjorgensen** [comment]
And I can confirm that using a job description with ALWMLTTHD(*YES) on ADDJOBSCDE will make the call to ServiceCommander through QP2SHELL2 run as expected. :+1: 

The job scheduler command
```
CALL PGM(QP2SHELL2) PARM('/QOpenSys/usr/bin/sh' '-c' '/QOpenSys/pkgs/bin/sc start all')
```

generates the following QPRINT output:
```
Performing operation 'START' on service 'repo-73_server'                                
Service 'IBM 7.3 synchronized repository server' successfully started                   
For details, see log file at: /home/NCCJ/.sc/logs/2021-05-14-11.05.02.repo-73_server.log
Performing operation 'START' on service 'repo_server'                                   
Service 'IBM synchronized repository server' successfully started                       
For details, see log file at: /home/NCCJ/.sc/logs/2021-05-14-11.05.05.repo_server.log   
```

Two for one - this PR is a bargain! :1st_place_medal:

**Comment by chrjorgensen** [comment]
My conclusion is to always use the STRTCPSVR support for starting and stopping ServiceCommander services.
This is much easier, much less error-prone - and much more IBM i like.

Thanks for developing this!

**Comment by ThePrez** [comment]
Thanks for helping to test and verify, and finding a legit CCSID-related bug! I think this Q is resolved, but feel free to reopen if there's anything still pending.
