### ISSUE TITLE
Postgres sample should be updated to submit to batch as a different user

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#5]
Apparently postgres needs to run as the same user that created the database. The sample, perhaps, should include a submit to batch as a different user, as I believe @richardschoen needed to do to align with his published Postgres doc.

**Comment by richardschoen** [comment]
Tweaked the Postgres sample to add submit to batch.

**Comment by ThePrez** [comment]
Thanks!
