### ISSUE TITLE
[FEATURE-REQUEST] Uninstall script for TCP server

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#50]
**Describe the solution you'd like**
I would like to have an uninstall script for cleanly removing the STRTCPSVR function.

Currently there is no controlled way to remove the TCP server and the  SCOMMANDER (or whatever the user specified during install) library. Like there is an install script I would like to have an uninstall script.

**Describe alternatives you've considered**
Manually removing the TCP server and the SC library. This requires looking into the code to see what commands were performed during installation, and perform the opposite.

**Additional context**

**Comment by ThePrez** [comment]
Closed by #49. Thanks!
