### ISSUE TITLE
[BUG] Install TCP server fails when compiling C module

### ISSUE THREAD

**Issue by chrjorgensen** [ThePrez/ServiceCommander-IBMi#77]
**Describe the bug**
When I run the install_tcp_server script, the command CRTCMOD fails. The issue is that the CRTCMOD command specifies TGTRLS(V7R1M0) but no ILE C *PRV compiler is installed.

**To Reproduce**
Run install_tcp_server on a IBM i 7.2 or higher with no ILE C *PRV compiler.

**Expected behavior**
The script should compile to current release - if compile to previous release is required, this should be an optional parameter to the script.

**Verbose output**
$ /QOpenSys/pkgs/lib/sc/tcpsvr/install_sc_tcpsvr
```
Command is > CRTLIB LIB(SCOMMANDER) TEXT('Service Commander')  <
CPF2111: Library SCOMMANDER already exists.
lib doesn't exist yet
Command is > DLTMOD MODULE(SCOMMANDER/SC)  <
CPC2191: Object SC in SCOMMANDER type *MODULE deleted.
Command is > DLTPGM PGM(SCOMMANDER/SC)  <
CPC2191: Object SC in SCOMMANDER type *PGM deleted.
Command is > RMVTCPSVR SVRSPCVAL(*SC)  <
TCP1640: TCP/IP server *SC removed successfully.
Command is > CRTCMOD MODULE(SCOMMANDER/SC) SRCSTMF('/QOpenSys/pkgs/lib/sc/tcpsvr/sc_tcpsvr.c') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) TGTCCSID(37) TGTRLS(V7R1M0)  <
CZS0601: Module SC is not created because statement errors occurred.
CZM0613: The compilation failed.
```

**Comment by ThePrez** [comment]
Fixed by #78
