### ISSUE TITLE
[FEATURE-REQUEST] man page for `scopenports`

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#84]
`man scopenports`

**Comment by AndyYouens** [comment]
@ThePrez okay for me to take this one?

**Comment by ThePrez** [comment]
Absolutely!! But please work off the `v1.0.0` branch as I tweaked the Makefile and instructions for the man page build. 

The short of it is that I write the man page in markdown and then use pandoc

Cheers!
