### ISSUE TITLE
[BUG] sc -a Argument not recognised

### ISSUE THREAD

**Issue by AndyYouens** [ThePrez/ServiceCommander-IBMi#95]
The readme.md states that sc -a checkall will show all, whereas the command returns a warning. 

sc -a check all
WARNING: Argument '-a' unrecognized and will be ignored

if this is just a readme change, do you want me to put in a PR?

**Comment by ThePrez** [comment]
@AndyYouens , thanks for the bug report! The `-a` argument is new in v1.x, which hasn't hit the IBM repo yet. 

In the interim, you can upgrade by running:
```bash
yum install https://github.com/ThePrez/ServiceCommander-IBMi/releases/download/v1.0.1/service-commander-1.0.1-0.ibmi7.2.ppc64.rpm
```

**Comment by AndyYouens** [comment]
That works.  Thanks @ThePrez
