### ISSUE TITLE
PORT env var

### ISSUE THREAD

**Issue by worksofliam** [ThePrez/ServiceCommander-IBMi#96]
**Describe the solution you'd like**

When prompted for port number in the `scinit` CLI:

```
Which ports does your application run on? Separate with commas, or leave blank for none:  8123
```

I think it should also make that number an environment variable by default in the yaml.

**Describe alternatives you've considered**

```
PORT=1234 scinit node index.js
```

```
What other environment variables from this current process should be used?
        (press <enter> after each entry, leave blank to entering values)
1> PORT
```

**Comment by ThePrez** [comment]
Will be addressed in v1.0.3+
